### ISSUE TITLE
`IllegalArgumentException: Too large value` on changing the window size

### ISSUE THREAD

**Issue by koeppl** [vigna/webgraph#1]
I would like to ask whether I have to exchange some parameter when modifying the window size for a recompression of a WebGraph.
When using an invocation like

`java -Xmx100G it.unimi.dsi.webgraph.BVGraph -w 64 /scratch/data/webgraph/uk-2014-hc-t /scratch/data/webgraph/uk-2014-hc-t`

I receive the following error message:

```
09:58:45.405 [main] INFO it.unimi.dsi.webgraph.BVGraph - Loading offsets...
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at it.unimi.dsi.webgraph.ImmutableGraph.load(ImmutableGraph.java:675)
    at it.unimi.dsi.webgraph.ImmutableGraph.loadMapped(ImmutableGraph.java:550)
    at it.unimi.dsi.webgraph.BVGraph.main(BVGraph.java:2390)
Caused by: java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at it.unimi.dsi.webgraph.ImmutableGraph.load(ImmutableGraph.java:671)
    ... 2 more
Caused by: java.lang.IllegalArgumentException: Too large value: 38965632897 > 38965632889
    at it.unimi.dsi.sux4j.util.EliasFanoMonotoneLongBigList.<init>(EliasFanoMonotoneLongBigList.java:306)
    at it.unimi.dsi.sux4j.util.EliasFanoMonotoneLongBigList.<init>(EliasFanoMonotoneLongBigList.java:274)
    at it.unimi.dsi.webgraph.BVGraph.loadInternal(BVGraph.java:1506)
    at it.unimi.dsi.webgraph.BVGraph.load(BVGraph.java:1302)
    at it.unimi.dsi.webgraph.BVGraph.loadMapped(BVGraph.java:1350)
    ... 7 more
```

This invocation works for smaller graphs, but neither for `uk-2014-hc-t` nor `gsh-2015-hc-t`.

I am using webgraph version 3.6.10 with OpenJDK 11.0.9.1.

**Comment by vigna** [comment]
Do I read correctly that you are overwriting the graph while recompressing it?

**Comment by koeppl** [comment]
Thanks for your quick answer, and also the solution to my problem. 
It seems that the framework can perform recompression while overwriting the graph when taking a small graph instance - at least the output seemed reasonable to me. Does that mean that the framework uses a fixed but sufficiently large buffer for the recompression such that I ended up in experiencing this undefined behavior (basically my fault) just as the graph sizes grew larger? (Anyhow, I have to admit that one should write the recompressed graph to a different file.)

**Comment by vigna** [comment]
Absolutely not. Recompression happens in streaming. You cannot recompress on the same file, period. I don't even know how you could ever think you could be able to do that...

**Comment by koeppl** [comment]
Thanks for the clarification! At least the results looked "okayish" on small graph instances. But maybe the files were buffered by the Java VM, which is my only explanation at hand for the behavior I experienced.

**Comment by vigna** [comment]
There's certainly some internal buffering, but the same phenomenon you can experience with any UN*X command. Try with sort, for example.

**Comment by koeppl** [comment]
My common experience is that when creating a file handle for output, you usually truncate the file on writing. So when input equals output, this would result in reading an empty file, something like
```C++
#include <iostream>
#include <fstream>
int main(const int argc, const char *const argv[]) {
	std::ifstream ifs(argv[1]);
	std::ofstream ofs(argv[2]);
	char c;
	while(c = ifs.get()) {
		if(!ifs) break;
		ofs.put(c);
	}
	return 0;
}
```
